name: Push Latest Docker Image

on:
  release:
    types: [edited]

jobs:
  push-latest-docker:
    runs-on: ubuntu-latest
    # Only run when the release becomes the latest (non-prerelease)
    if: github.event.release.latest == true && github.event.release.prerelease == false
    
    steps:
      - name: Echo - Starting checkout
        run: echo "🚀 Starting checkout of code for release ${{ github.event.release.tag_name }}"