apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wiremock
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  sources:
    - chart: wiremock
      repoURL: 'ghcr.io/deliveryhero/helm-charts'
      targetRevision: '1.4.6'
      helm:
        releaseName: wiremock
        valueFiles:
          - $values/values.yaml
    - repoURL: 'https://github.com/savanipoojan78/kubernetes-job-with-argocd'
      ref: values
      targetRevision: HEAD
  project: default