apiVersion: v1
kind: Pod
metadata:
  name: test-container
spec:
  containers:
  - name: test-container
    image: nginx
    imagePullPolicy: IfNotPresent
    volumes:
      - name: test
        persistentVolumeClaim:
          claimName: test-data
