apiVersion: v1
data:
  DATABASE_URI: dGVzdDI=
kind: Secret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
    argocd.argoproj.io/hook: PreSync
  name: test-b9tg4b94dkq
  namespace: default
type: Opaque