apiVersion: v1
data:
  DATABASE_URI: dGVzdDQ=
kind: Secret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
    # argocd.argoproj.io/hook: PreSync
  name: test-b9tg4b94dkd
  namespace: default
type: Opaque