apiVersion: v1
data:
  DATABASE_URI: dGVzdA==
kind: Secret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
    argocd.argoproj.io/hook: PreSync
  name: test-b9tg4b94dk
  namespace: default
type: Opaque