apiVersion: v1
data:
  DATABASE_URI: ref+gcpsecrets://ddn-9ee785f5-107b-4fbd-9d8f-59/promptql-custom#DB_URL2
kind: Secret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
    # argocd.argoproj.io/hook: PreSync
  name: test
  namespace: default
type: Opaque